database:
 host:
 port:
 database:
 user:
 password:
 poolsize: 10
 connectionTimeout: 10000
 idleTimeout: 600000
 maxLifetime: 7200000
aggregate_period: 60000
period_delay_count: 6
period_future_count: 3
server: local
